theme: jekyll-theme-modernist

title: Welcome to Sam Cookson's Programming Portfolio

author: Sam Cookson

author_email: sbcskyline18@gmail.com

description: Programming portfolio consisting of school programming projects as well as Spy Hop programming projects which are designed to confront educational, social, and environmental issues in our local and global community.
